version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
    command: bun run preview

  dev:
    image: jarredsumner/bun:latest
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=development
    command: bun run dev